# Base image
FROM ubuntu

# Do image configuration
RUN /bin/bash -c 'echo This would generally be apt-get'

# Define the environment variables
ENV myCustomEnvVar="This is a sample" \
    otherEnvVar="This is also a sample"
